name: Android SDK Setup

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install OpenJDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Install Android SDK Command-line Tools
      run: |
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-6858069_latest.zip
        unzip -q commandlinetools-linux-6858069_latest.zip -d android-sdk
        echo "y" | android-sdk/tools/bin/sdkmanager --sdk_root=android-sdk/tools --licenses
