name: Python Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Adjust the Node.js version as needed

      - name: Check Node.js and npm version
        run: |
          node -v
          npm -v
          
      - name: Install Appium and Appium UIAutomator2 driver
        run: |
          npm install -g appium@2.4.1
          npm install appium-uiautomator2-driver@3.0.4 --save-dev
          appium -v
          appium driver list --installed
          
      - name: Create Android emulator
        run: |
          echo "no" | avdmanager --verbose create avd --force --name "test_emulator" --package "system-images;android-29;google_apis;x86" --abi "x86" --device "pixel" --sdcard 512M

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run tests
        run: |
          xvfb-run -a pytest --alluredir=./allure_results
      
      - name: Generate Allure report
        run: |
          allure generate ./allure_results -o ./allure-report --clean
          
      - name: Upload Allure report artifacts
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: ./allure-report
