name: Mobile Automation Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macos-12

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install allure-pytest

      - name: Set up Node.js and Appium
        run: |
          npm install -g appium
          appium -v

      - name: Install Appium Drivers
        run: |
          appium driver install uiautomator2
          appium driver install xcuitest

      - name: Print Node.js Version
        run: node -v

      - name: Print ADB Devices
        run: adb devices

      - name: Clean Allure Results Directory
        run: |
          if [ -d "allure-results" ]; then rm -rf allure-results; fi
          if [ -d "allure-report" ]; then rm -rf allure-report; fi

      - name: Install Allure CLI
        run: |
          wget -O allure-2.14.0.zip -q https://github.com/allure-framework/allure2/releases/download/2.14.0/allure-2.14.0.zip
          unzip -q allure-2.14.0.zip -d $HOME
          echo "export PATH=$HOME/allure-2.14.0/bin:$PATH" >> $HOME/.bash_profile
          source $HOME/.bash_profile

      - name: Run Appium Android Tests
        run: |
          adb devices
          pytest --alluredir=./allure-results --capture=sys

      - name: Print Allure Results Directory Contents
        run: |
          echo "Contents of allure-results directory:"
          ls -l allure-results

      - name: Upload Allure Results
        uses: actions/upload-artifact@v2
        with:
          name: allure-results
          path: allure-results

      - name: Generate Allure Report
        run: |
          source $HOME/.bash_profile
          allure generate allure-results -o allure-report --clean

      - name: Print Allure Report Directory Contents
        run: |
          echo "Contents of allure-report directory:"
          ls -l allure-report

      - name: Upload Allure Report
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: allure-report

      - name: Zip Allure Report
        run: |
          zip -r allure-report.zip allure-report

      - name: Upload Allure Report Zip
        uses: actions/upload-artifact@v2
        with:
          name: allure-report-zip
          path: allure-report.zip
