name: UI Automator Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  setup-and-run-tests:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Check Node.js and npm version
        run: |
          node -v
          npm -v
          
      - name: Install Appium and Appium UIAutomator2 driver
        run: |
          npm install -g appium@2.4.1
          npm install appium-uiautomator2-driver@3.0.4 --save-dev
          appium -v
          appium driver list --installed

      - name: Add Android SDK tools to PATH
        run: |
          echo "##[add-path]${{ env.ANDROID_HOME }}/cmdline-tools/latest/bin"
          echo "##[add-path]${{ env.ANDROID_HOME }}/emulator"
          echo "##[add-path]${{ env.ANDROID_HOME }}/tools"
          echo "##[add-path]${{ env.ANDROID_HOME }}/platform-tools"
          echo "##[add-path]${{ env.ANDROID_HOME }}/build-tools/${{ env.ANDROID_BUILD_TOOLS_VERSION }}"

      - name: Start Android Emulator
        run: |
          # Start the emulator here, replacing $EMULATOR_NAME with your emulator name
          emulator @$EMULATOR_NAME -no-snapshot -no-audio -no-window

      - name: Wait for Emulator to Boot
        run: |
          # Wait for the emulator to fully boot before proceeding with tests
          adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done; input keyevent 82'

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run tests
        run: |
          pytest --alluredir=./allure_results
      
      - name: Generate Allure report
        run: |
          allure generate ./allure_results -o ./allure-report --clean
          
      - name: Upload Allure report artifacts
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: ./allure-report
