name: UI Automator Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  run-python-tests:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Check Node.js and npm version
        run: |
          node -v
          npm -v
          
      - name: Install Appium and Appium UIAutomator2 driver
        run: |
          npm install -g appium@2.4.1
          npm install appium-uiautomator2-driver@3.0.4 --save-dev
          appium -v
          appium driver list --installed

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run tests
        run: |
          pytest --alluredir=./allure_results
      
      - name: Generate Allure report
        run: |
          allure generate ./allure_results -o ./allure-report --clean
          
      - name: Upload Allure report artifacts
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: ./allure-report

  run-uiautomator-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List root directory
        run: ls $GITHUB_WORKSPACE

      - name: List .github directory
        run: ls $GITHUB_WORKSPACE/.github

      - name: List workflows directory
        run: ls $GITHUB_WORKSPACE/.github/workflows

      - name: List files in snippet_uiautomator/android directory
        run: ls $GITHUB_WORKSPACE/UI_Automator/android

      - name: Set up ADB
        run: sudo apt-get install -y android-tools-adb

      - name: Install APK on device
        run: adb install $GITHUB_WORKSPACE/UI_Automator/android/uiautomator.apk

      - name: Run UI Automator tests
        run: adb shell uiautomator runtest $GITHUB_WORKSPACE/UI_Automator/android/test.jar -c com.example.TestClass
