name: UI Automator Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  setup-and-run-tests:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Check Node.js and npm version
        run: |
          node -v
          npm -v
          
      - name: Install Allure CLI
        run: |
          Invoke-WebRequest -Uri "https://github.com/allure-framework/allure2/releases/download/2.14.0/allure-2.14.0.zip" -OutFile "allure-2.14.0.zip"
          Expand-Archive -Path "allure-2.14.0.zip" -DestinationPath "C:\allure-2.14.0"
          $env:Path += ";C:\allure-2.14.0\allure-2.14.0\bin"
          allure --version
          
      - name: Set up Android SDK
        run: |
          echo "ANDROID_HOME=${{ env.ANDROID_HOME }}" >> $GITHUB_ENV
          echo "PATH=${{ env.ANDROID_HOME }}/cmdline-tools/latest/bin;${{ env.ANDROID_HOME }}/emulator;${{ env.ANDROID_HOME }}/tools;${{ env.ANDROID_HOME }}/platform-tools;${{ env.ANDROID_HOME }}/build-tools/${{ env.ANDROID_BUILD_TOOLS_VERSION }}:$PATH" >> $GITHUB_ENV
          
      - name: Start Android Emulator
        run: |
          "${{ env.ANDROID_HOME }}/emulator/emulator @$EMULATOR_NAME -no-snapshot -no-audio -no-window"
          
     
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Allure CLI
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.14.0/allure-2.14.0.zip
          unzip allure-2.14.0.zip -d /tmp
          sudo mv /tmp/allure-2.14.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure
          allure --version
          
      - name: Run tests
        run: |
          python run_tests.py
      
      - name: Generate Allure report
        run: |
          allure generate ./allure_results -o ./allure-report --clean
          
      - name: Upload Allure report artifacts
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: ./allure-report
