name: UI Automator Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  run-uiautomator-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up ADB
        run: sudo apt-get install -y android-tools-adb

      - name: Set up environment variables
        run: |
          echo "CONFIG_PATH=$(pwd)/snippet_uiautomator/android/uiautomator.apk" >> $GITHUB_ENV

      - name: Install APK on device
        run: adb install $CONFIG_PATH

      - name: Run UI Automator tests
        run: |
          test_path="$(pwd)/snippet_uiautomator/android/test.jar"
          adb shell uiautomator runtest $test_path -c com.example.TestClass
