name: Android SDK Setup and Python Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  android_sdk_and_python_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install OpenJDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Install Android SDK Command-line Tools
        run: |
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-6858069_latest.zip
          unzip -q commandlinetools-linux-6858069_latest.zip -d android-sdk
          echo "y" | android-sdk/tools/bin/sdkmanager --sdk_root=android-sdk/tools --licenses

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Check Node.js and npm version
        run: |
          node -v
          npm -v
          
      - name: Install Appium and Appium UIAutomator2 driver
        run: |
          npm install -g appium@2.4.1
          npm install appium-uiautomator2-driver@3.0.4 --save-dev
          appium -v
          appium driver list --installed
          
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run tests
        run: |
          xvfb-run -a pytest --alluredir=./allure_results
      
      - name: Generate Allure report
        run: |
          allure generate ./allure_results -o ./allure-report --clean
          
      - name: Upload Allure report artifacts
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: ./allure-report

