trigger:
  - master

pool:
  vmImage: ubuntu-latest

strategy:
  matrix:
    Python27:
      python.version: '2.7'
    Python35:
      python.version: '3.5'
    Python36:
      python.version: '3.6'
    Python37:
      python.version: '3.7'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
    displayName: 'Use Python $(python.version)'

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: |
      pip install pytest pytest-azurepipelines
      pytest
    displayName: 'pytest'

- name: Set up Node.js
  uses: actions/setup-node@v2
  with:
    node-version: '14' # Adjust as needed

- name: Check Node.js and npm version
  run: |
    node -v
    npm -v

- name: Install Appium
  run: |
    npm install -g appium@latest
    npm install appium-uiautomator2-driver@3.0.4 --save-dev
    appium -v
    appium driver list --installed

- name: Set up Python
  uses: actions/setup-python@v2
  with:
    python-version: 3.9

- name: Install dependencies
  run: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt

- name: Run tests
  run: xvfb-run -a pytest
